# Generated by Django 4.0.1 on 2022-09-21 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeauthpc',
            name='start_date',
            field=models.DateTimeField(db_column='StartDate', default=django.utils.timezone.now, verbose_name='StartDate'),
        ),
        migrations.AlterField(
            model_name='employeeauthsc',
            name='start_date',
            field=models.DateTimeField(db_column='StartDate', default=django.utils.timezone.now, verbose_name='StartDate'),
        ),
        migrations.AlterField(
            model_name='employeerequesthistory',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='StartDate'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='UpdatedDateTime'),
        ),
    ]
