# Generated by Django 4.0.1 on 2022-09-25 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_alter_employeeauthpc_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitcenterstaging',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='profitcenterstaging',
            name='status',
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='approver',
            field=models.ForeignKey(blank=True, db_column='approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='business_unit',
            field=models.CharField(blank=True, db_column='BusinessUnit', max_length=50, verbose_name='BusinessUnit'),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='comments',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='is_active',
            field=models.BooleanField(db_column='Status', default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='requester',
            field=models.ForeignKey(blank=True, db_column='requester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='sbu',
            field=models.CharField(blank=True, db_column='SBU', max_length=50, verbose_name='SBU'),
        ),
        migrations.AddField(
            model_name='profitcenterstaging',
            name='state',
            field=models.CharField(db_column='state', default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='business_brand',
            field=models.CharField(blank=True, db_column='BusinessBrand', max_length=50, null=True, verbose_name='BusinessBrand'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='business_geography',
            field=models.CharField(blank=True, db_column='BusinessGeography', max_length=50, null=True, verbose_name='BusinessGeography'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='business_segment',
            field=models.CharField(blank=True, db_column='BusinessSegment', max_length=50, null=True, verbose_name='BusinessSegment'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='flash_pg',
            field=models.CharField(blank=True, db_column='FlashPG', max_length=50, null=True, verbose_name='FlashPG'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='me_tel_pg',
            field=models.CharField(blank=True, db_column='MeTelPG', max_length=50, null=True, verbose_name='MeTelPG'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='mis_business_unit',
            field=models.CharField(blank=True, db_column='MISBusinessUnit', max_length=50, null=True, verbose_name='MISBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='mis_business_vertical',
            field=models.CharField(blank=True, db_column='MISBusinessVertical', max_length=50, null=True, verbose_name='MISBusinessVertical'),
        ),
        migrations.AlterField(
            model_name='profitcenter',
            name='product_group',
            field=models.CharField(blank=True, db_column='ProductGroup', max_length=50, null=True, verbose_name='ProductGroup'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='business_brand',
            field=models.CharField(blank=True, db_column='BusinessBrand', max_length=50, null=True, verbose_name='BusinessBrand'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='business_geography',
            field=models.CharField(blank=True, db_column='BusinessGeography', max_length=50, null=True, verbose_name='BusinessGeography'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='business_line',
            field=models.CharField(blank=True, db_column='BusinessLine', max_length=50, null=True, verbose_name='BusinessLine'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='business_segment',
            field=models.CharField(blank=True, db_column='BusinessSegment', max_length=50, null=True, verbose_name='BusinessSegment'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='client',
            field=models.IntegerField(db_column='Client', default=300, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='company_code',
            field=models.CharField(db_column='CompanyCode', max_length=4, verbose_name='CompanyCode'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDateTime', verbose_name='CreatedDateTime'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='flash_pg',
            field=models.CharField(blank=True, db_column='FlashPG', max_length=50, null=True, verbose_name='FlashPG'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='me_tel_pg',
            field=models.CharField(blank=True, db_column='MeTelPG', max_length=50, null=True, verbose_name='MeTelPG'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='mis_business_unit',
            field=models.CharField(blank=True, db_column='MISBusinessUnit', max_length=50, null=True, verbose_name='MISBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='mis_business_vertical',
            field=models.CharField(blank=True, db_column='MISBusinessVertical', max_length=50, null=True, verbose_name='MISBusinessVertical'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='product_group',
            field=models.CharField(blank=True, db_column='ProductGroup', max_length=50, null=True, verbose_name='ProductGroup'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='profit_center_code',
            field=models.CharField(db_column='ProfitCenterCode', max_length=10, verbose_name='ProfitCenterCode'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='profit_center_desc',
            field=models.CharField(db_column='ProfitCenterDesc', max_length=50, verbose_name='ProfitCenterDesc'),
        ),
        migrations.AlterField(
            model_name='profitcenterstaging',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedDateTime', verbose_name='UpdatedDateTime'),
        ),
        migrations.DeleteModel(
            name='ProfitCenterHistory',
        ),
    ]
