# Generated by Django 4.0.1 on 2022-09-12 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_code', models.CharField(db_column='EmployeeCode', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='EmployeeCode')),
                ('employee_name', models.CharField(db_column='EmployeeName', max_length=255, verbose_name='EmployeeName')),
                ('email', models.EmailField(db_column='EmailID', max_length=254, unique=True, verbose_name='EmailID')),
                ('email_by_code', models.EmailField(blank=True, db_column='EmailByCode', default=None, max_length=254, null=True, unique=True, verbose_name='EmailByCode')),
                ('email_by_name', models.EmailField(blank=True, db_column='EmailByName', default=None, max_length=254, null=True, unique=True, verbose_name='EmailByName')),
                ('work_country', models.CharField(blank=True, db_column='WorkCountry', max_length=50, null=True, verbose_name='WorkCountry')),
                ('sbu', models.CharField(blank=True, db_column='SBU', max_length=10, verbose_name='SBU')),
                ('owner_name', models.CharField(blank=True, db_column='OwnerEmployeeName', default=None, max_length=255, null=True, verbose_name='OwnerEmployeeName')),
                ('owner_email', models.EmailField(blank=True, db_column='OwnerEmployeeEmailID', default=None, max_length=254, null=True, verbose_name='OwnerEmployeeEmailID')),
                ('job_title', models.CharField(blank=True, db_column='JobTitle', max_length=100, verbose_name='JobTitle')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', verbose_name='CreatedDate')),
                ('exit_date_time', models.DateTimeField(blank=True, db_column='ExitedDate', null=True, verbose_name='ExitedDate')),
                ('is_active', models.BooleanField(db_column='Status', default=True, verbose_name='isActive')),
                ('is_admin', models.BooleanField(db_column='IsAdmin', default=False, verbose_name='isSuperUser')),
                ('is_owner', models.BooleanField(db_column='IsOwner', default=False, verbose_name='IsOwner')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, db_column='OwnerEmployeeCode', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 't_Employee',
                'verbose_name_plural': 't_Employee',
            },
        ),
    ]
