# Generated by Django 4.0.1 on 2022-10-12 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_employee',
            name='create_date_time',
            field=models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now, verbose_name='CreatedDate'),
        ),
    ]
